### ISSUE TITLE
Teensy 3.6 - CAN 2.0B and CAN FD Demo Board

### ISSUE THREAD

**Issue by craigtao** [skpang/Teensy36_with_MCP2517FD_CAN_FD_demo_LCD#1]
Teensy 3.6 - CAN 2.0B and CAN FD Demo Board

i want to buy one，but i don't know how to pay for, address and.....

i come from china,

can you help me?

craig

**Comment by skpang** [comment]
Just purchase this item from the store:
http://skpang.co.uk/catalog/teensy-36-can-20b-and-can-fd-demo-board-p-1551.html
