### ISSUE TITLE
A couple of questions if i might

### ISSUE THREAD

**Issue by mjs513** [skpang/Teensy36_with_MCP2517FD_CAN_FD_demo_LCD#2]
Right now I am using a MCP2517FD CLick as I mentioned in the other issue I opened with a Teensy3.5 (think it should work as well as the T3.6) and in going through the sketch not sure of the transmit construct you are using:
1.  It looks like you are sending 4 bytes with txd[4] through txd[7] but you are also shifting the byte by 24, 16 and 8.  txd is defined as uint8_t's.  4 bytes is a 32bit's or doubles?
2.  Why aren't you using txf[0] to txd[3] ?
3.  Why is DLC 15 versus 8 since the packet is 8 bytes.

Also I am not sure packets are being transmitted - anyway to confirm this?

thanks
Mike

**Comment by gannaramu** [comment]
Were you able to get the transmit working?
